name: andyjgill
favicon: null
layout_spectrum: 0.4637123045977205
typography_spectrum: 0.4206187736708671
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9087958775926381
  lightness: 0.3082822891883552
  saturation: 0.3316818776074797
  rhythmicContrast: 0.8800470733549446
purpose: []
